const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');

test('homepage retains the film contract, current routes and accessible page structure', () => {
  const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]);
  assert.equal(new Set(ids).size, ids.length);
  assert.equal((html.match(/<h1\b/g) || []).length, 1);
  assert.equal((html.match(/<main\b/g) || []).length, 1);
  for (const id of ['manufacturingJourney', 'journeyCanvas', 'journeyTitle', 'journeyCaption', 'journeyKicker', 'journeyLoading', 'journeyProgress', 'afterJourney']) assert.ok(ids.includes(id), id);
  assert.equal((html.match(/class="journey-step(?: is-active)?"/g) || []).length, 5);
  assert.equal((html.match(/class="hv-material"/g) || []).length, 4);
  assert.ok(html.includes('footer-complete'));
  assert.ok(html.includes('https://cutitout.uk/guidelines'));
  assert.ok(html.includes('We only stock textured powder coat.'));
  assert.ok(html.includes('<noscript>'));
  assert.equal((html.match(/<video\b/g) || []).length, 1);
  assert.ok(html.includes('id="workshopVideo" muted loop playsinline preload="metadata"'));
  assert.ok(html.includes('id="workshopVideoToggle"'));
  assert.ok(html.includes('class="hv-hero-shade"'));
  assert.ok(html.includes('class="journey-continue"'));
  assert.ok(html.includes('/static/js/journey-end-stop.js'));
  assert.ok(html.includes('/static/img/company/workshop-team.webp'));
  assert.ok(!html.includes('Follow an illustrated metal part'));
  assert.ok(!html.includes('family-workshop-final.webp'));
  assert.ok(fs.readFileSync(path.join(root, 'company/index.html'), 'utf8').includes('family-workshop-final.webp'));
  assert.ok(html.includes('You design it.<br><span>We’ll Cut It Out.</span>'));
  assert.ok(!html.includes('setInterval'));
  assert.ok(!html.includes('900 x 900'));
});
