// Mechanical header sync: preserve page content, share a single source and export.
// Run from any directory: node scripts/sync-header.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const write = (file, value) => fs.writeFileSync(path.join(root, file), value);
const template = read('components/header.html');
const css = read('static/css/site-header.css');
const js = read('static/js/shared-header.js');
const version = '20260915-public-routes';
const pages = ['index.html', 'materials/index.html', 'services/index.html', 'contact/index.html', 'company/index.html', 'delivery-returns/index.html', 'privacy/index.html', 'terms/index.html', 'guidelines/index.html'];
function header({portable=false} = {}) {
  return template.replaceAll('{{HOME}}', 'https://cutitout.uk/')
    .replaceAll('{{MARKETING}}', 'https://cutitout.uk')
    .replaceAll('{{GUIDELINES}}', 'https://cutitout.uk/guidelines/')
    .replaceAll('{{LOGO}}', portable ? 'data:image/svg+xml;base64,' + Buffer.from(read('static/img/home/cut-it-out-white.svg')).toString('base64') : '/static/img/home/cut-it-out-white.svg');
}
for (const file of pages) {
  let html = read(file);
  const old = /[ \t]*<header\b[^>]*class="[^"]*(?:site-header|cio-header)[^"]*"[^>]*>[\s\S]*?<\/header>\s*/g;
  if ([...html.matchAll(old)].length !== 1) throw new Error(`Expected one header in ${file}`);
  html = html.replace(old, '').replace(/(<body[^>]*>)\s*/, (_, tag) => tag + '\n' + header());
  html = html.replace("document.querySelector('#siteMenuToggle').onclick=()=>{let n=document.querySelector('#siteMenu');n.classList.toggle('is-open')};", '');
  html = html.replace("document.querySelector('#siteMenuToggle').onclick=()=>document.querySelector('#siteMenu').classList.toggle('is-open')", '');
  html = html.replace(/(<div class="(?:shell|dc-shell)">)\s+(?=<)/g, '$1\n');
  // Remove our previous includes only; leave unrelated page assets untouched.
  html = html.replace(/\s*<link[^>]+href="\/static\/css\/site-header\.css[^" ]*"[^>]*>/g, '')
    .replace(/\s*<script[^>]+src="\/static\/js\/shared-header\.js[^" ]*"[^>]*><\/script>/g, '');
  html = html.replace('</head>', `  <link rel="stylesheet" href="/static/css/site-header.css?v=${version}">\n  <script src="/static/js/shared-header.js?v=${version}" defer></script>\n</head>`);
  write(file, html);
}
// The existing standalone header preview now uses the real shared component.
write('mobile-header.html', `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex"><title>Cut It Out header</title><style>body{margin:0;background:#f7f8f6}</style><link rel="stylesheet" href="/static/css/site-header.css?v=${version}"><script src="/static/js/shared-header.js?v=${version}" defer></script></head><body>\n${header()}\n</body></html>\n`);
const portable = `<!-- CUT IT OUT: PORTABLE HEADER\nPaste this entire fragment immediately after the app layout's opening body tag.\nReplace the old header and its menu handler; do not nest inside a padded wrapper.\nCSS, embedded white SVG logo, HTML and JavaScript are all included.\nOnly one copy per page. No framework, fonts, image files or libraries required.\nIf your Content Security Policy blocks inline styles/scripts or data images, move\nthese sections into approved assets or apply your app's existing nonce mechanism.\nAccount links to /my-account; retain the app's existing authentication handling.\nDo not add fake login state or a fixed cart count. For client-side routing, initialize\nthe script once after mounting and let the app update aria-current on navigation.\nSource: components/header.html, static/css/site-header.css, static/js/shared-header.js.\nGenerated by scripts/sync-header.mjs.\n-->\n<style>\n${css}</style>\n${header({portable:true})}\n<script>\n${js}</script>\n`;
write('shared-header.html', portable);
// The independently deployed offline page must not depend on marketing assets.
let fallback = read('cloudflare_app_fallback/index.html');
fallback = fallback.replace(/<!-- CUT IT OUT: PORTABLE HEADER[\s\S]*?<\/script>\s*/, '');
fallback = fallback.replace(/<header class="topbar">[\s\S]*?<\/header>/, '');
fallback = fallback.replace(/<body>\s*/, '<body>\n' + portable);
fallback = fallback.replace(/(<div class="shell">)\s+(?=<)/g, '$1\n');
write('cloudflare_app_fallback/index.html', fallback);
console.log(`Updated ${pages.length + 1} website headers, offline page and shared-header.html.`);
